apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: anyuid
  name: db-debug
spec:
  containers:
  - command:
    - tail
    args:
    - -f
    - /dev/null
    env:
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: DBSECRET
          key: db.password
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          name: DBSECRET
          key: db.user
    - name: PGHOST
      valueFrom:
        secretKeyRef:
          name: DBSECRET
          key: db.host
    - name: PGPORT
      valueFrom:
        secretKeyRef:
          name: DBSECRET
          key: db.port
    - name: PGDATABASE
      valueFrom:
        secretKeyRef:
          name: DBSECRET
          key: db.name
    image: quay.io/jlindgren/consoledot-debugger:master
    name: db-debugger
    resources:
      limits:
        cpu: 100m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 128Mi
    stdin: true
    stdinOnce: true
    tty: true
  restartPolicy: Never
