apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: anyuid
  name: db-debug
spec:
  containers:
  - command:
    - tail
    args:
    - -f
    - /dev/null
    image: quay.io/jlindgren/consoledot-debugger:master
    name: db-debugger
    resources:
      limits:
        cpu: 2
        memory: 6Gi
      requests:
        cpu: 50m
        memory: 128Mi
    stdin: true
    stdinOnce: true
    tty: true
  restartPolicy: Never
