apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: anyuid
  name: POD_NAME
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  containers:
  - command:
    - tail
    args:
    - -f
    - /dev/null
    env:
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: DBSECRET
          key: db.password
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          name: DBSECRET
          key: db.user
    - name: PGHOST
      valueFrom:
        secretKeyRef:
          name: DBSECRET
          key: db.host
    - name: PGPORT
      valueFrom:
        secretKeyRef:
          name: DBSECRET
          key: db.port
    - name: PGDATABASE
      valueFrom:
        secretKeyRef:
          name: DBSECRET
          key: db.name
    - name: ACG_CONFIG
      value: /cdapp/cdappconfig.json
    image: IMAGE
    name: POD_NAME
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 128Mi
    stdin: true
    stdinOnce: true
    tty: true
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /tmp
      name: rds-client-ca
    - mountPath: /cdapp/
      name: config-secret
  restartPolicy: Never
  volumes:
  - emptyDir: {}
    name: rds-client-ca
  - name: config-secret
    secret:
      optional: true
      defaultMode: 420
      secretName: CLOWDAPP
